### PR TITLE
Add pull to refresh to all grid views

### PR DESCRIPTION
**Pull request by Jawnnypoo**
Added pull to refresh on all fragments that extend BaseGridFragment.

### CODE REVIEW

**Comment by Jawnnypoo** [comment]
Sorry about that. That was for when I was testing it. The only potential issue I could see now is that this allows refresh on screens that were not previously refreshable, such as Subreddit and Topics. Should we include some sort of toggle in the base class to determine if we want pull to refresh on the grid or not?

**Comment by Kennyc1012** [comment]
Having a refresh on topics and subreddits is not an issue. I would also like to see a refresh icon in the action bar as I am not a fan of pull to refresh (which is why I never did it myself anyways). But you don't have to include that in this commit, I can add it later.

**Comment by Jawnnypoo** [comment]
I went ahead and added the refresh button to the toolbar on subreddits too. I was mistaken and it was already present on topics. Looks like Topics already had the button, but was not actually refreshing on press. So I went ahead and added that. Let me know if there is anything else you want me to do in order to accept.

**Comment by Kennyc1012** [comment]
Looks good to me, I'll probably be pushing an update some time tonight for the app with miscellaneous fixes. I will take a close look at this after the release.

**Comment by Kennyc1012** [comment]
I have a few nit picks regarding this commit, but I will address myself.

**Pull request merged**
