### PR TITLE
Use HTTPS protocol in external links.

### PR DESCRIPTION
**Pull request by zamabe**
These websites are capable of secure communication and future technologies require secure connections to be used in major implementations (SPDY/HTTP2).

PS. Noob here, still fumbling around with building to apk to verify these are the necessary/desired changes. Would appreciate correction of any errors/mistakes.

### CODE REVIEW

**Comment by Kennyc1012** [comment]
I'll be creating wiki on importing and successfully building the project later tonight. Everything looks good, I will run some test later and merge if everything is good, thanks!

**Comment by zamabe** [comment]
`EDIT: Just noticed you pushed to master. Please make all pushes to development.`

No, I pushed to `zamabe:https`. Did you want me to push to a branch named development or just one not named master?

**Comment by Kennyc1012** [comment]
No I mean you submitted the pull request into Kennyc1012:master. Do any pull requests to the development branch.

**Comment by zamabe** [comment]
ah, you want me to request the pull to your master. #44

**Pull request closed without merging**
